using System.Text.Json.Serialization;
using Application.Dto_s.Responses;
using Domain.Contracts.CleanModels;
using Domain.Enums;
using Mediator;
using Newtonsoft.Json.Converters;
using DriveType = System.IO.DriveType;

namespace Application.UseCases.Queries;

public record GetByFilterQuery(
    [property: JsonConverter(typeof(StringEnumConverter))]
    BodyType? BodyType,
    int? MinCost,
    int? MaxCost,
    int? MinYear,
    int? MaxYear,
    [property: JsonConverter(typeof(StringEnumConverter))]
    EngineType? EngineType,
    [property: JsonConverter(typeof(StringEnumConverter))]
    TransmissionType? TransmissionType,
    DriveType? DriveType,
    float? MinHeight,
    float? MaxHeight,
    float? MinWidth,
    float? MaxWidth,
    float? MinLength,
    float? MaxLength,
    float? FrontWheelBase,
    float? BackWheelBase,
    string? Clearance,
    float? VolumeLiters,
    int? MinHorsePower,
    int? MaxHorsePower,
    float? MinConsumptionMixed,
    float? MaxConsumptionMixed,
    string? Seats,
    int? TrunksMinCapacity,
    int? TrunksMaxCapacity,
    
    int PageNumber,
    int PageSize,
    bool? Camera360,
    bool? AshtrayAndCigaretteLighter,
    bool? AutoCruise,
    bool? AutoMirrors,
    bool? AutoPark ,
    ClimateControl? ClimateControl,
    bool? Computer ,
    bool? Condition ,
    bool? CoolingBox ,
    bool? CruiseControl ,
    bool? DriveModeSystem ,
    bool? EasyTrunkOpening ,
    bool? ElectroMirrors ,
    bool? ElectroTrunk ,
    bool? ElectroWindowBack ,
    bool? ElectroWindowFront ,
    bool? ElectronicGagePanel,
    bool? FrontCamera ,
    bool? KeylessEntry,
    bool? MultiFunctionSteeringWheel,
    bool? ParkAssistFront ,
    bool? ParkAssistRear ,
    bool? PowerLatchingDoors ,
    bool? ProgrammedBlockHeater,
    bool? ProjectionDisplay,
    bool? RearCamera ,
    bool? RemoteEngineStart ,
    bool? Servo ,
    bool? StartButton ,
    bool? StartStopFunction ,
    bool? SteeringWheelGearShiftPaddles ,
    string? WheelHightConfiguration,
    string? WheelDistanceConfiguration ,
    bool? WheelMemory ,
    bool? WheelPower ,
    bool? Socket12V,
    bool? Socket220V ,
    bool? AndroidAuto ,
    bool? AudioPreparation ,
    bool? CdAudioSystem ,
    bool? TVAudioSystem ,
    bool? PremiumAudio ,
    bool? Multimedia,
    bool? AUX ,
    bool? AppleCarplay ,
    bool? Bluetooth ,
    bool? Navigation ,
    bool? USB ,
    bool? VoiceRecognition ,
    bool? WirelessCharger,
    bool? YaAuto ,
    bool? HeatedSteeringWheel ,
    bool? DriverSeatSupport ,
    bool? SeatUpDown,
    bool? ElectroRegulatingSeat ,
    bool? SeatSupport ,
    bool? SeatsHeat,
    bool? SeatsHeatVent ,
    bool? MassageSeats,
    IEnumerable<string>? MarkIds = null,
    IEnumerable<string>? ModelIds = null) : IQuery<IEnumerable<GetByFilterResponse>>;